/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MealManagementSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author tiger
 */
public class SetupDatabase extends javax.swing.JFrame {

     public String username = "";
     public String password = "";
    public SetupDatabase() {
        initComponents();
   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnStartSetup = new javax.swing.JButton();
        txtPassConfirm = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prepair Database");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Test Connection");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnStartSetup.setText("Setup Database");
        btnStartSetup.setEnabled(false);
        btnStartSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSetupActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("What will be your login information? give me below.");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        txtStatus.setBackground(new java.awt.Color(0, 204, 204));
        txtStatus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("Status...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Database Table Setup Section");

        jButton2.setText("Test Your Inputs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStartSetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnStartSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DBSetup dbs = new DBSetup();
        String server = dbs.getServer();
        String database = dbs.getDatabase();
        String user = dbs.getUser();
        String pass = dbs.getPass();
        
        Connection con;
        Statement st;
        try {
            con = DriverManager.getConnection("jdbc:mysql://"+server+"/"+database,user,pass);
            int confirm = showConfirmDialog(null,"Database Connection Success\n Are you sure that database is empty?");
            System.out.println(confirm);
            if(confirm == 0){
                btnStartSetup.setEnabled(true);
                jButton1.setEnabled(false); 
            }
          
        } catch (SQLException ex) {
            //Logger.getLogger(SetupDatabase.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null,"Database Connection Error!");
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnStartSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSetupActionPerformed
          DBSetup dbs = new DBSetup();
        String server = dbs.getServer();
        String database = dbs.getDatabase();
        String user = dbs.getUser();
        String pass = dbs.getPass();
        
        String createAdminTable = "CREATE TABLE admin(id INT(20) NOT NULL AUTO_INCREMENT,username VARCHAR(50) NOT NULL,email VARCHAR(100) NOT NULL,password VARCHAR(100) NOT NULL,PRIMARY KEY (id))";
           String createBazarTable = "CREATE TABLE bazar(id INT(20) NOT NULL AUTO_INCREMENT,name VARCHAR(50) NOT NULL,date VARCHAR(20) NOT NULL,total VARCHAR(20) NOT NULL,details VARCHAR(1000) NOT NULL,PRIMARY KEY (id))";
           String createMamberTable = "CREATE TABLE mamber(id INT(20) NOT NULL AUTO_INCREMENT,name VARCHAR(50) NOT NULL,meal VARCHAR(10) NOT NULL,payment VARCHAR(10) NOT NULL,bazar VARCHAR(10) NOT NULL,PRIMARY KEY (id))";

           String createMealTable = "CREATE TABLE meal(id INT(20) NOT NULL AUTO_INCREMENT,name VARCHAR(50) NOT NULL,date VARCHAR(20) NOT NULL,total VARCHAR(20) NOT NULL,PRIMARY KEY (id))";
           String createNoteTable = "CREATE TABLE note(id INT(20) NOT NULL AUTO_INCREMENT,note VARCHAR(5000) NOT NULL,PRIMARY KEY (id))";
           String createPaymentTable = "CREATE TABLE payment(id INT(20) NOT NULL AUTO_INCREMENT,name VARCHAR(50) NOT NULL,date VARCHAR(20) NOT NULL,total VARCHAR(20) NOT NULL,PRIMARY KEY (id))";
           String InsertNote = "INSERT INTO note (id, note) VALUES (NULL, 'empty NOte')";
           String InserAdmin = "INSERT INTO admin (id, username, email, password) VALUES (NULL, '"+this.username+"', 'test@test.com', '"+this.password+"')";
         
             try {
             Connection con;
             Statement st;
             ResultSet rs;
             con = DriverManager.getConnection("jdbc:mysql://"+server+"/"+database,user,pass);
             
              st = con.createStatement();
            
                 txtStatus.setText("Creating Admin Table...");
               try {
                   st.execute(createAdminTable);
                   txtStatus.setText("Table Created Successfully!"); 
               } catch (SQLException ex) {
                   showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                   //Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
               }
                                     
                
                 txtStatus.setText("Creating Bazar Table...");
               try {
                   st.execute(createBazarTable);
                   txtStatus.setText("Bazar Table Created Successfully.."); 
               } catch (SQLException ex) {
                   showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                   //Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
               }
                                  
          
               txtStatus.setText("Creating Mamber Table...");
               try{
                  st.execute(createMamberTable);  
                  txtStatus.setText("Mamber Table Created Successfully");
               }catch(SQLException ex){
                   showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                   //System.out.println(ex);
               }
              
              
              txtStatus.setText("Creating Meal Table..");
              try{
              st.execute(createMealTable);
              txtStatus.setText("Meal Table Created Successfully");
              }catch(SQLException ex){
                  showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                  //System.out.println(ex);
              }  
              
              
              txtStatus.setText("Creating Note Table..");
              try{
              st.execute(createNoteTable);
              txtStatus.setText("Note Table Created Successfully");
              }catch(SQLException ex){
                  showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                  //System.out.println(ex);
              }  
              
              
              txtStatus.setText("Creating Payment Table..");
              try{
              st.execute(createPaymentTable);
              txtStatus.setText("Payment Table Created Successfully");
              }catch(SQLException ex){
                  showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                  //System.out.println(ex);
              }
              
              
              txtStatus.setText("Inserting Empty data to Note Table..");
              try{
              st.execute(InsertNote);
                 txtStatus.setText("Empty note inserted Successfully");
              }catch(SQLException ex){
                  showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                  //System.out.println(ex);
              }
              
           
              txtStatus.setText("Inserting admin login information..");
              try{
              st.execute(InserAdmin);
              txtStatus.setText("Inserted admin login Successfully..");
              }catch(SQLException ex){
                  showMessageDialog(null,"Data Already Exists!");
                   this.dispose();
                  //System.out.println(ex);
                  
              }
             
              txtStatus.setText("\n\n Congratulation You are ready to go..");

                 
             } catch (SQLException ex) {
                 //Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
                 txtStatus.setText("Something Error! Make sure database is Empty!!");
                 
             }
    }//GEN-LAST:event_btnStartSetupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String user = txtUser.getText().trim();
         String pass = txtPass.getText().trim();
         String passConfirm = txtPassConfirm.getText().trim();
         
         if(user.isEmpty() == true && pass.isEmpty() == true && passConfirm.isEmpty() == true){
             showMessageDialog(null,"You should Enter your username and password");
             
         }else if(pass.equals(passConfirm)){
             jButton1.setEnabled(true);
             jButton2.setEnabled(false);
             this.username = user;
             this.password = pass;
             txtUser.setEditable(false);
             txtPass.setEditable(false);
             txtPassConfirm.setEditable(false);
         }else{
             showMessageDialog(null,"Your password not matched!!");
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartSetup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassConfirm;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
